In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from utils import load_json

In [2]:
def get_best_results(json_fname):
    results = load_json(json_fname)
    best_results = []
    super_keys = []
    for missing_percent in range(5, 25, 5):
        missing_percent = str(missing_percent)
        df = pd.DataFrame(results[missing_percent])
        df['sub_auc'] = 1 - df.auc
        df['score'] = df.nrmse + df.error + df.sub_auc
        for fold in range(5):
            im = df.loc[df.fold == fold].score.idxmin()
            best_result = dict(df.loc[im])
            best_result.update({'missing_percent': missing_percent,
                               'fold': fold})
            best_results.append(best_result)

    best_results = pd.DataFrame(best_results)
    best_results.missing_percent = best_results.missing_percent.astype('int')
    return best_results

In [3]:
churn = get_best_results('./results/1119churn_DSAN.json')
churn.groupby('missing_percent').mean().round(4)

                 epoch  fold   nrmse   error     auc  sub_auc   score
missing_percent
5                 31.4     2  0.9625  0.3436  0.8323   0.1677  1.4739
10                44.2     2  0.9725  0.3576  0.8320   0.1680  1.4981
15                30.2     2  0.9685  0.3549  0.8316   0.1684  1.4918
20                35.2     2  0.9757  0.3665  0.8307   0.1693  1.5115

In [4]:
churn.groupby('missing_percent').mean().mean(axis=0)

epoch      35.250000
fold        2.000000
nrmse       0.969810
error       0.355655
auc         0.831620
sub_auc     0.168380
score       1.493845
dtype: float64

In [5]:
online = get_best_results("./results/1115online_DSAN.json")
online.groupby('missing_percent').mean().round(4)

                 epoch  fold   nrmse   error     auc  sub_auc   score
missing_percent
5                 68.4     2  0.6311  0.3366  0.8951   0.1049  1.0726
10                61.8     2  0.6413  0.3465  0.8970   0.1030  1.0908
15                55.0     2  0.6619  0.3498  0.8964   0.1036  1.1154
20                56.2     2  0.6738  0.3569  0.8984   0.1016  1.1322

In [6]:
online.groupby('missing_percent').mean().mean(axis=0)

epoch      60.350000
fold        2.000000
nrmse       0.652015
error       0.347450
auc         0.896730
sub_auc     0.103270
score       1.102735
dtype: float64

In [7]:
bank = get_best_results("./results/1115bank_DSAN.json")
bank.groupby('missing_percent').mean().round(4)

                 epoch  fold   nrmse   error     auc  sub_auc   score
missing_percent
5                 71.2     2  0.7580  0.2501  0.9028   0.0972  1.1053
10                77.0     2  0.7860  0.2571  0.9029   0.0971  1.1403
15                95.8     2  0.8282  0.2678  0.9029   0.0971  1.1931
20                75.8     2  0.8226  0.2732  0.9020   0.0980  1.1938

In [8]:
bank.groupby('missing_percent').mean().mean(axis=0)

epoch      79.950000
fold        2.000000
nrmse       0.798695
error       0.262065
auc         0.902650
sub_auc     0.097350
score       1.158110
dtype: float64

In [9]:
adult = get_best_results("./results/1115adult_DSAN.json")
adult.groupby('missing_percent').mean().round(4)

                 epoch  fold   nrmse   error     auc  sub_auc   score
missing_percent
5                 88.0     2  0.7999  0.2103  0.9050   0.0950  1.1052
10                84.6     2  0.8099  0.2173  0.9050   0.0950  1.1222
15                77.2     2  0.8247  0.2239  0.9047   0.0953  1.1440
20                90.2     2  0.8488  0.2325  0.9045   0.0955  1.1769

In [10]:
adult.groupby('missing_percent').mean().mean(axis=0)

epoch      85.000000
fold        2.000000
nrmse       0.820860
error       0.221015
auc         0.904800
sub_auc     0.095200
score       1.137075
dtype: float64

In [11]:
def get_best_results(json_fname):
    results = load_json(json_fname)
    best_results = []
    super_keys = []
    for missing_percent in range(5, 25, 5):
        missing_percent = str(missing_percent)
        df = pd.DataFrame(results[missing_percent])
        df['sub_auc'] = 1 - df.auc
        df['score'] = df.nrmse + df.error
        for fold in range(5):
            im = df.loc[df.fold == fold].score.idxmin()
            best_result = dict(df.loc[im])
            best_result.update({'missing_percent': missing_percent,
                               'fold': fold})
            best_results.append(best_result)

    best_results = pd.DataFrame(best_results)
    best_results.missing_percent = best_results.missing_percent.astype('int')
    return best_results

In [12]:
churn = get_best_results('./results/1119churn_DSAN.json')
churn.groupby('missing_percent').mean().round(4)

                 epoch  fold   nrmse   error     auc  sub_auc   score
missing_percent
5                 31.4     2  0.9625  0.3436  0.8323   0.1677  1.3062
10                46.2     2  0.9726  0.3575  0.8315   0.1685  1.3301
15                29.8     2  0.9681  0.3550  0.8310   0.1690  1.3232
20                30.2     2  0.9755  0.3666  0.8304   0.1696  1.3422

In [13]:
churn.groupby('missing_percent').mean().mean(axis=0)

epoch      34.400000
fold        2.000000
nrmse       0.969685
error       0.355705
auc         0.831305
sub_auc     0.168695
score       1.325390
dtype: float64

In [14]:
online = get_best_results("./results/1115online_DSAN.json")
online.groupby('missing_percent').mean()

                 epoch  fold    nrmse    error      auc  sub_auc    score
missing_percent
5                 68.6     2  0.63138  0.33616  0.89490  0.10510  0.96754
10                69.8     2  0.64176  0.34566  0.89628  0.10372  0.98742
15                49.6     2  0.66106  0.35028  0.89596  0.10404  1.01134
20                65.0     2  0.67374  0.35616  0.89488  0.10512  1.02990

In [15]:
online.groupby('missing_percent').mean().mean(axis=0)

epoch      63.250000
fold        2.000000
nrmse       0.651985
error       0.347065
auc         0.895505
sub_auc     0.104495
score       0.999050
dtype: float64

In [16]:
bank = get_best_results("./results/1115bank_DSAN.json")
bank.groupby('missing_percent').mean()

                 epoch  fold    nrmse    error      auc  sub_auc    score
missing_percent
5                 71.2     2  0.75800  0.25014  0.90282  0.09718  1.00814
10                77.0     2  0.78598  0.25714  0.90286  0.09714  1.04312
15                94.4     2  0.82918  0.26664  0.90266  0.09734  1.09582
20                69.4     2  0.82198  0.27380  0.90188  0.09812  1.09578

In [17]:
bank.groupby('missing_percent').mean().mean(axis=0)

epoch      78.000000
fold        2.000000
nrmse       0.798785
error       0.261930
auc         0.902555
sub_auc     0.097445
score       1.060715
dtype: float64

In [18]:
adult = get_best_results("./results/1115adult_DSAN.json")
adult.groupby('missing_percent').mean()

                 epoch  fold    nrmse    error      auc  sub_auc    score
missing_percent
5                 83.0     2  0.79970  0.21046  0.90498  0.09502  1.01016
10                86.0     2  0.80978  0.21742  0.90494  0.09506  1.02720
15                69.0     2  0.82484  0.22384  0.90466  0.09534  1.04868
20                90.2     2  0.84884  0.23254  0.90446  0.09554  1.08138

In [19]:
adult.groupby('missing_percent').mean().mean(axis=0)

epoch      82.050000
fold        2.000000
nrmse       0.820790
error       0.221065
auc         0.904760
sub_auc     0.095240
score       1.041855
dtype: float64